apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-7jwj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-7jwj
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-7jwj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-7jwj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-7jwj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mpis-tenant/status-quarkus-io/statusquarkusio-7jwj@sha256:f1c9314ed5d85aadca924a5827820798393947ab73459f93b0b98d3a6ea1ac25
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
